export const BUILD_TIME_PER_PLANK = 10;
export const BUILD_TIME_PER_STONE = 15;

export const BUILDING_TYPES = {
  HEADQUARTERS: { id: 'headquarters', name: 'Штаб', width: 3, height: 3, constructionMaterials: {}, terrainIds: null, workerTypeId: null, toolId: null, workRadius: null, influenceRadius: 10, input: {}, output: null, productionTime: null, role: 'storage' },
  WAREHOUSE: { id: 'warehouse', name: 'Склад', width: 3, height: 3, constructionMaterials: { planks: 3, stone: 3 }, terrainIds: ['plains'], workerTypeId: null, toolId: null, workRadius: null, input: {}, output: null, productionTime: null, role: 'storage' },
  FORESTER_HUT: { id: 'forester_hut', name: 'Хижина лесника', width: 2, height: 2, constructionMaterials: { planks: 2 }, terrainIds: ['plains'], workerTypeId: 'forester', toolId: 'shovel', workRadius: 8, input: {}, output: { resourceId: 'wood', amount: 1 }, productionTime: 10, role: 'production' },
  STONECUTTER_HUT: { id: 'stonecutter_hut', name: 'Хижина каменщика', width: 2, height: 2, constructionMaterials: { planks: 2 }, terrainIds: ['plains'], workerTypeId: 'stonemason', toolId: 'pickaxe', workRadius: 5, input: {}, output: { resourceId: 'stone', amount: 1 }, productionTime: 10, role: 'extraction' },
  SAWMILL: { id: 'sawmill', name: 'Лесопилка', width: 2, height: 3, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'lumberjack', toolId: 'axe', workRadius: 5, input: { wood: 1 }, output: { resourceId: 'planks', amount: 1 }, productionTime: 15, role: 'production' },
  WELL: { id: 'well', name: 'Колодец', width: 2, height: 2, constructionMaterials: { planks: 2 }, terrainIds: ['plains'], workerTypeId: 'resident', toolId: null, workRadius: null, input: {}, output: { resourceId: 'water', amount: 1 }, productionTime: 15, role: 'production' },
  FARM: { id: 'farm', name: 'Ферма', width: 4, height: 4, constructionMaterials: { planks: 4, stone: 3 }, terrainIds: ['plains'], workerTypeId: 'farmer', toolId: 'scythe', workRadius: null, workArea: { width: 4, height: 4, usableCells: 14 }, input: {}, output: { resourceId: 'wheat', amount: 1 }, productionTime: 30, role: 'production' },
  MILL: { id: 'mill', name: 'Мельница', width: 2, height: 2, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'miller', toolId: 'bag', workRadius: null, input: { wheat: 1 }, output: { resourceId: 'flour', amount: 1 }, productionTime: 15, role: 'production' },
  BAKERY: { id: 'bakery', name: 'Пекарня', width: 2, height: 2, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'baker', toolId: 'rolling_pin', workRadius: null, input: { flour: 1, water: 1 }, output: { resourceId: 'bread', amount: 1 }, productionTime: 15, role: 'production' },
  COAL_MINE: { id: 'coal_mine', name: 'Угольная шахта', width: 2, height: 2, constructionMaterials: { planks: 4 }, terrainIds: ['hills', 'mountains'], workerTypeId: 'miner', toolId: 'pickaxe', workRadius: 5, input: { food: 1 }, output: { resourceId: 'coal', amount: 1 }, productionTime: 15, role: 'extraction' },
  IRON_MINE: { id: 'iron_mine', name: 'Железная шахта', width: 2, height: 2, constructionMaterials: { planks: 4 }, terrainIds: ['hills', 'mountains'], workerTypeId: 'miner', toolId: 'pickaxe', workRadius: 5, input: { food: 1 }, output: { resourceId: 'iron', amount: 1 }, productionTime: 15, role: 'extraction' },
  GOLD_MINE: { id: 'gold_mine', name: 'Золотая шахта', width: 2, height: 2, constructionMaterials: { planks: 4 }, terrainIds: ['hills', 'mountains'], workerTypeId: 'miner', toolId: 'pickaxe', workRadius: 5, input: { food: 1 }, output: { resourceId: 'gold', amount: 1 }, productionTime: 15, role: 'extraction' },
  MARBLE_MINE: { id: 'marble_mine', name: 'Мраморная шахта', width: 2, height: 2, constructionMaterials: { planks: 4 }, terrainIds: ['hills', 'mountains'], workerTypeId: 'miner', toolId: 'pickaxe', workRadius: 5, input: { food: 1 }, output: { resourceId: 'stone', amount: 1 }, productionTime: 15, role: 'extraction' },
  FOUNDRY: { id: 'foundry', name: 'Плавильня', width: 2, height: 2, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'steelworker', toolId: 'ladle', workRadius: null, input: { iron: 1, coal: 1 }, output: { resourceId: 'steel', amount: 1 }, productionTime: 15, role: 'production' },
  FORGE: { id: 'forge', name: 'Кузница', width: 2, height: 2, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'blacksmith', toolId: 'hammer', workRadius: null, input: { steel: 1, coal: 1 }, output: { resourceId: 'sword', amount: 1 }, productionTime: 15, role: 'production' },
  WORKSHOP: { id: 'workshop', name: 'Цех', width: 3, height: 3, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'master', toolId: 'tongs', workRadius: null, input: { steel: 1, planks: 1 }, output: { resourceId: 'tool', amount: 1 }, productionTime: 15, role: 'production' },
  MINT: { id: 'mint', name: 'Монетный двор', width: 2, height: 2, constructionMaterials: { planks: 2, stone: 2 }, terrainIds: ['plains'], workerTypeId: 'steelworker', toolId: 'ladle', workRadius: null, input: { gold: 1, coal: 1 }, output: { resourceId: 'coin', amount: 1 }, productionTime: 15, role: 'production' },
  OUTPOST: { id: 'outpost', name: 'Форпост', width: 2, height: 2, constructionMaterials: { planks: 3 }, terrainIds: ['plains'], workerTypeId: 'soldier', toolId: null, workRadius: null, input: {}, output: null, productionTime: null, influenceMultiplier: 0.75, requiredSoldiers: 1, role: 'military' },
  BARRACKS: { id: 'barracks', name: 'Казарма', width: 3, height: 3, constructionMaterials: { planks: 3, stone: 1 }, terrainIds: ['plains'], workerTypeId: 'soldier', toolId: null, workRadius: null, input: {}, output: null, productionTime: null, influenceMultiplier: 1, requiredSoldiers: 3, role: 'military' },
  WATCHTOWER: { id: 'watchtower', name: 'Сторожевая башня', width: 2, height: 2, constructionMaterials: { planks: 5, stone: 5 }, terrainIds: ['plains'], workerTypeId: 'soldier', toolId: null, workRadius: null, input: {}, output: null, productionTime: null, influenceMultiplier: 1.25, requiredSoldiers: 6, role: 'military' },
  FORTRESS: { id: 'fortress', name: 'Крепость', width: 5, height: 5, constructionMaterials: { planks: 10, stone: 10 }, terrainIds: ['plains'], workerTypeId: 'soldier', toolId: null, workRadius: null, input: {}, output: null, productionTime: null, influenceMultiplier: 1.5, requiredSoldiers: 9, blockChanceBonus: 0.05, role: 'military' },
};
function findType(typeId) { return Object.values(BUILDING_TYPES).find((item) => item.id === typeId) ?? null; }
export function getConstructionTime(materials = {}) { return Number(materials.planks ?? 0) * BUILD_TIME_PER_PLANK + Number(materials.stone ?? 0) * BUILD_TIME_PER_STONE; }
export function getConstructionMaterials(building) { return { ...(findType(building.typeId)?.constructionMaterials ?? {}) }; }
export function createBuilding(id, ownerId, typeId, tileId) { const type = findType(typeId); if (!type) throw new Error(`Unknown building type: ${typeId}`); const required = getConstructionMaterials({ typeId }); const complete = Object.keys(required).length === 0; return { id, ownerId, typeId, tileId, active: complete, constructionComplete: complete, constructionMaterialsRequired: required, constructionMaterialsDelivered: Object.fromEntries(Object.keys(required).map((resource) => [resource, 0])), constructionQueue: [], currentConstructionMaterial: null, currentConstructionMaterialRemainingTime: 0, workerIds: [], soldierIds: [], constructionTimer: 0 }; }
export function deliverConstructionMaterial(building, resourceId, amount = 1) { if (!building || building.constructionComplete) return 0; const required = Number(building.constructionMaterialsRequired?.[resourceId] ?? 0); const delivered = Number(building.constructionMaterialsDelivered?.[resourceId] ?? 0); const units = Math.max(0, Math.min(Math.floor(Number(amount) || 0), required - delivered)); if (!units) return 0; building.constructionMaterialsDelivered[resourceId] = delivered + units; for (let i = 0; i < units; i += 1) building.constructionQueue.push(resourceId); if (!building.currentConstructionMaterial) startNextConstructionMaterial(building); return units; }
function startNextConstructionMaterial(building) { const next = building.constructionQueue.shift(); if (!next) return false; building.currentConstructionMaterial = next; building.currentConstructionMaterialRemainingTime = next === 'stone' ? BUILD_TIME_PER_STONE : next === 'planks' ? BUILD_TIME_PER_PLANK : 0; building.constructionTimer = building.currentConstructionMaterialRemainingTime; building.constructionState = 'BUILDING'; return true; }
export function advanceConstruction(building, elapsedSeconds) { if (!building || building.constructionComplete) return building; let remaining = Math.max(0, Number(elapsedSeconds) || 0); if (!building.currentConstructionMaterial) startNextConstructionMaterial(building); while (remaining > 0 && building.currentConstructionMaterial) { const work = Math.min(remaining, building.currentConstructionMaterialRemainingTime); building.currentConstructionMaterialRemainingTime -= work; building.constructionTimer = building.currentConstructionMaterialRemainingTime; remaining -= work; if (building.currentConstructionMaterialRemainingTime === 0) { building.currentConstructionMaterial = null; building.constructionTimer = 0; if (remaining > 0) startNextConstructionMaterial(building); } } const allDelivered = Object.entries(building.constructionMaterialsRequired).every(([resource, amount]) => building.constructionMaterialsDelivered[resource] >= amount); if (allDelivered && !building.currentConstructionMaterial && !building.constructionQueue.length) { building.constructionComplete = true; building.active = true; building.constructionState = 'COMPLETED'; } else if (!building.currentConstructionMaterial && !building.constructionQueue.length) building.constructionState = 'WAITING_FOR_MATERIAL'; return building; }
export function getBuildingType(building) { return findType(building.typeId); }
export function getFootprintTiles(state, typeId, originTileId) { const type = findType(typeId); const origin = state.tiles.find((tile) => tile.id === originTileId); if (!type || !origin) return []; const footprint = []; for (let dy = 0; dy < type.height; dy += 1) for (let dx = 0; dx < type.width; dx += 1) { const tile = state.tiles.find((candidate) => candidate.x === origin.x + dx && candidate.y === origin.y + dy); if (!tile) return []; footprint.push(tile); } return footprint; }
export function getReservedTiles(state, typeId, originTileId) { const footprint = getFootprintTiles(state, typeId, originTileId); if (!footprint.length) return []; const coords = new Set(footprint.map((tile) => `${tile.x},${tile.y}`)); return state.tiles.filter((tile) => !coords.has(`${tile.x},${tile.y}`) && footprint.some((cell) => Math.max(Math.abs(tile.x - cell.x), Math.abs(tile.y - cell.y)) === 1)); }
export function getBuildingAtTile(state, tileId) { return (state.buildings ?? []).find((building) => getFootprintTiles(state, building.typeId, building.tileId).some((tile) => tile.id === tileId)) ?? null; }
export function isReservedForBuilding(state, tileId) { return (state.buildings ?? []).some((building) => getReservedTiles(state, building.typeId, building.tileId).some((tile) => tile.id === tileId)); }
export function canBuildOnTile(state, typeId, tileId, ownerId = state.player.id) { const type = findType(typeId); const footprint = getFootprintTiles(state, typeId, tileId); if (!type || footprint.length !== type.width * type.height) return false; if (footprint.some((tile) => tile.ownerId !== ownerId)) return false; if (type.terrainIds && footprint.some((tile) => !type.terrainIds.includes(tile.terrain))) return false; if (footprint.some((tile) => getBuildingAtTile(state, tile.id) || isReservedForBuilding(state, tile.id))) return false; return true; }
export function addBuilding(state, building) { if (!canBuildOnTile(state, building.typeId, building.tileId, building.ownerId)) throw new Error('Building cannot be placed on this footprint'); state.buildings ??= []; state.buildings.push(building); return building; }
