import { rebuildLogisticsNetwork } from './logisticsNetwork.js';

const DIRECTIONS = [[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]];
const MAX_ROADS_PER_FLAG = 4;
const MIN_ROAD_CELLS = 2;
const MAX_ROAD_CELLS = 20;
function tileId(x,y){return `${x}-${y}`;}
function getTile(state,id){return state.tiles.find(t=>t.id===id)??null;}
function getFlag(state,id){return(state.flags??[]).find(f=>f.id===id)??null;}
function tileCenter(tile){return{x:tile.x+0.5,y:tile.y+0.5};}
function adjacentToNode(tile,node){if(!tile||!node)return false;const c=tileCenter(tile);return Math.max(Math.abs(c.x-node.x),Math.abs(c.y-node.y))===0.5;}
function areAdjacent(a,b){return Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y))===1;}
function directionIndex(dx,dy){return DIRECTIONS.findIndex(([x,y])=>x===Math.sign(dx)&&y===Math.sign(dy));}
function directionChange(a,b){if(a==null||b==null)return 0;const d=Math.abs(a-b);return Math.min(d,DIRECTIONS.length-d);}
function countRoadsForFlag(state,id){return(state.roads??[]).filter(r=>r.active&&(r.startFlagId===id||r.endFlagId===id)).length;}
function occupiedRoadCells(state){return new Set((state.roads??[]).filter(r=>r.active).flatMap(r=>r.cells));}
function segmentsCross(a,b,c,d){const o=(p,q,r)=>Math.sign((q.y-p.y)*(r.x-q.x)-(q.x-p.x)*(r.y-q.y));const on=(p,q,r)=>Math.min(p.x,r.x)<=q.x&&q.x<=Math.max(p.x,r.x)&&Math.min(p.y,r.y)<=q.y&&q.y<=Math.max(p.y,r.y);const[o1,o2,o3,o4]=[o(a,b,c),o(a,b,d),o(c,d,a),o(c,d,b)];return(o1!==o2&&o3!==o4)||(o1===0&&on(a,c,b))||(o2===0&&on(a,d,b))||(o3===0&&on(c,a,d))||(o4===0&&on(c,b,d));}
function roadsIntersect(state,candidate,existing){const cs=getFlag(state,candidate.startFlagId),ce=getFlag(state,candidate.endFlagId),es=getFlag(state,existing.startFlagId),ee=getFlag(state,existing.endFlagId);if(!cs||!ce||!es||!ee)return false;for(let i=0;i<candidate.cells.length-1;i++)for(let j=0;j<existing.cells.length-1;j++){const a=getTile(state,candidate.cells[i]),b=getTile(state,candidate.cells[i+1]),c=getTile(state,existing.cells[j]),d=getTile(state,existing.cells[j+1]);if(!a||!b||!c||!d||!segmentsCross(a,b,c,d))continue;const ca=i===0||i===candidate.cells.length-2,ea=j===0||j===existing.cells.length-2;if(ca&&ea){const cf=i===0?candidate.startFlagId:candidate.endFlagId,ef=j===0?existing.startFlagId:existing.endFlagId;if(cf===ef)continue;}return true;}return false;}
export function createRoad(id,startFlagId,endFlagId,cells=[]){return{id,startFlagId,endFlagId,cells:[...cells],active:true};}
export function isRoadPathValid(state,road){const start=getFlag(state,road.startFlagId),end=getFlag(state,road.endFlagId);if(!start||!end||start.id===end.id||!Array.isArray(road.cells)||road.cells.length<MIN_ROAD_CELLS||road.cells.length>MAX_ROAD_CELLS)return false;const first=getTile(state,road.cells[0]),last=getTile(state,road.cells.at(-1));if(!adjacentToNode(first,start)||!adjacentToNode(last,end))return false;const seen=new Set(),occupied=occupiedRoadCells(state);occupied.delete(road.cells[0]);occupied.delete(road.cells.at(-1));let prev=null;for(let i=0;i<road.cells.length;i++){const id=road.cells[i],tile=getTile(state,id);if(!tile||seen.has(id))return false;seen.add(id);if(i>0){const p=getTile(state,road.cells[i-1]);if(!areAdjacent(p,tile))return false;const dir=directionIndex(tile.x-p.x,tile.y-p.y);if(dir<0||directionChange(prev,dir)>1)return false;prev=dir;}if(i>0&&i<road.cells.length-1&&occupied.has(id))return false;}for(const existing of state.roads??[])if(existing.active&&existing.id!==road.id&&roadsIntersect(state,road,existing))return false;return true;}
export function addRoad(state,road){if(!isRoadPathValid(state,road))throw new Error('Road path is invalid');state.roads??=[];if(state.roads.some(r=>r.id===road.id))throw new Error(`Road already exists: ${road.id}`);if(countRoadsForFlag(state,road.startFlagId)>=MAX_ROADS_PER_FLAG)throw new Error('Start flag has reached the road limit');if(countRoadsForFlag(state,road.endFlagId)>=MAX_ROADS_PER_FLAG)throw new Error('End flag has reached the road limit');state.roads.push(road);rebuildLogisticsNetwork(state);return road;}
export function removeRoad(state,id){const i=(state.roads??[]).findIndex(r=>r.id===id);if(i<0)return null;const[r]=state.roads.splice(i,1);rebuildLogisticsNetwork(state);return r;}
export function removeRoadsForFlag(state,id){const ids=(state.roads??[]).filter(r=>r.startFlagId===id||r.endFlagId===id).map(r=>r.id);for(const x of ids)removeRoad(state,x);return ids;}
export function getRoadAtTile(state,id){return(state.roads??[]).filter(r=>r.active&&r.cells.includes(id));}
function nodeOnPair(state,x,y,aId,bId){const a=getTile(state,aId),b=getTile(state,bId);if(!a||!b)return false;const ac=tileCenter(a),bc=tileCenter(b);return(ac.x+bc.x)/2===x&&(ac.y+bc.y)/2===y;}
export function getRoadAtNode(state,x,y){return(state.roads??[]).find(r=>r.active&&r.cells.some((id,i)=>i<r.cells.length-1&&nodeOnPair(state,x,y,id,r.cells[i+1])))??null;}
export function splitRoadAtNode(state,roadId,x,y,options={}){const road=(state.roads??[]).find(r=>r.id===roadId&&r.active);if(!road)return null;let split=-1;for(let i=0;i<road.cells.length-1;i++)if(nodeOnPair(state,x,y,road.cells[i],road.cells[i+1])){split=i;break;}if(split<0)return null;const first=road.cells.slice(0,split+1),second=road.cells.slice(split+1);if(first.length<MIN_ROAD_CELLS||second.length<MIN_ROAD_CELLS||first.length>MAX_ROAD_CELLS||second.length>MAX_ROAD_CELLS)return null;if(options.validateOnly)return{first,second,road};const flagId=options.flagId;if(!flagId||!getFlag(state,flagId))return null;const used=new Set(state.roads.map(r=>r.id));let id1=`${road.id}-1`,id2=`${road.id}-2`,n=2;while(used.has(id1)||used.has(id2)){id1=`${road.id}-1-${n}`,id2=`${road.id}-2-${n}`,n++;}const index=state.roads.indexOf(road);state.roads.splice(index,1,createRoad(id1,road.startFlagId,flagId,first),createRoad(id2,flagId,road.endFlagId,second));rebuildLogisticsNetwork(state);return[state.roads[index],state.roads[index+1]];}
export function getRoadNeighbors(state,id){const tile=getTile(state,id);if(!tile)return[];return DIRECTIONS.map(([dx,dy])=>tileId(tile.x+dx,tile.y+dy)).map(x=>getTile(state,x)).filter(Boolean).filter(c=>getRoadAtTile(state,c.id).some(r=>r.cells.includes(id)));}
function gridDistance(a,b){return Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));}
export function findNearestFlag(state,id){const start=getFlag(state,id);if(!start)return null;return(state.flags??[]).filter(f=>f.id!==id).sort((a,b)=>gridDistance(start,a)-gridDistance(start,b)||String(a.id).localeCompare(String(b.id)))[0]??null;}
function getShortestPaths(state,start,end){const blocked=occupiedRoadCells(state),endAdjacent=new Set();for(const t of state.tiles)if(adjacentToNode(t,end))endAdjacent.add(t.id);const starts=state.tiles.filter(t=>adjacentToNode(t,start)&&!blocked.has(t.id)),queue=[],dist=new Map(),parents=new Map();for(const t of starts){const s=`${t.id}|8`;dist.set(s,1);queue.push({x:t.x,y:t.y,d:8,s});}let head=0,target=null;while(head<queue.length){const cur=queue[head++],cd=dist.get(cur.s);if(target!=null&&cd>=target)continue;if(endAdjacent.has(cur.s.split('|')[0]))target=target==null?cd:Math.min(target,cd);for(let nd=0;nd<DIRECTIONS.length;nd++){if(cur.d!==8&&directionChange(cur.d,nd)>1)continue;const[dx,dy]=DIRECTIONS[nd],x=cur.x+dx,y=cur.y+dy,id=tileId(x,y),tile=getTile(state,id);if(!tile||blocked.has(id))continue;const ns=`${id}|${nd}`,d=cd+1,old=dist.get(ns);if(old==null||d<old){dist.set(ns,d);parents.set(ns,[cur.s]);queue.push({x,y,d:nd,s:ns});}else if(d===old)parents.get(ns).push(cur.s);}}if(target==null||target<MIN_ROAD_CELLS||target>MAX_ROAD_CELLS)return[];const ends=[...dist.entries()].filter(([s,d])=>d===target&&endAdjacent.has(s.split('|')[0])).map(([s])=>s),paths=[],seen=new Set(),path=[];function collect(s){path.push(s.split('|')[0]);if(dist.get(s)===1){const p=[...path].reverse(),k=p.join('|');if(!seen.has(k)){seen.add(k);paths.push(p);}path.pop();return;}for(const p of parents.get(s)??[])collect(p);path.pop();}for(const e of ends)collect(e);return paths;}
export function findShortestRoadPaths(state,startId,endId){const s=getFlag(state,startId),e=getFlag(state,endId);if(!s||!e||s.id===e.id)return[];if(countRoadsForFlag(state,startId)>=MAX_ROADS_PER_FLAG||countRoadsForFlag(state,endId)>=MAX_ROADS_PER_FLAG)return[];return getShortestPaths(state,s,e);}
function selectCompatiblePaths(state,paths){const selected=[],used=occupiedRoadCells(state);for(const p of paths){const interior=p.slice(1,-1);if(interior.some(c=>used.has(c)))continue;selected.push(p);for(const c of interior)used.add(c);}return selected;}
export function buildRoadToNearestFlag(state,startId,roadId){const start=getFlag(state,startId),end=findNearestFlag(state,startId);if(!start)throw new Error(`Unknown flag: ${startId}`);if(!end)return null;if(!roadId)throw new Error('Road id is required');const paths=selectCompatiblePaths(state,findShortestRoadPaths(state,startId,end.id));const cap=Math.min(MAX_ROADS_PER_FLAG-countRoadsForFlag(state,startId),MAX_ROADS_PER_FLAG-countRoadsForFlag(state,end.id)),selected=paths.slice(0,cap);if(!selected.length)return null;const roads=selected.map((cells,i)=>addRoad(state,createRoad(i===0?roadId:`${roadId}-${i+1}`,start.id,end.id,cells)));return roads.length===1?roads[0]:roads;}
