import { describe, expect, it } from 'vitest';
import { createGameState, MAP_WIDTH, MAP_HEIGHT, HEADQUARTERS_INFLUENCE_RADIUS, STARTER_FOREST_AREA, STARTER_STONE_AREA, STARTER_HILLS_AREA, STARTER_MOUNTAINS_AREA } from '../src/game/state.js';
import { BUILDING_TYPES, BUILD_TIME_PER_PLANK, BUILD_TIME_PER_STONE, advanceConstruction, canBuildOnTile, getFootprintTiles, getReservedTiles, isReservedForBuilding, createBuilding } from '../src/game/buildings.js';
import { deliverConstructionMaterial } from '../src/game/materials.js';
import { createGameClock, startGameClock, tickGameClock } from '../src/game/clock.js';
import { CONSTRUCTION_STATES, startConstruction } from '../src/game/construction.js';
import { INFLUENCE_RADIUS, isWithinInfluenceRadius } from '../src/game/influence.js';
import { WORKER_TYPES, createWorker, createWorkZone, assignWorkerToBuilding, workWorker } from '../src/game/workers.js';
import { createTerritorySource, addTerritorySource, getOwnedTiles } from '../src/game/territory.js';

describe('game clock', () => { it('starts at zero and advances by elapsed seconds', () => { const clock = createGameClock(); expect(clock.elapsedSeconds).toBe(0); startGameClock(clock, 1000); tickGameClock(clock, 3500); expect(clock.elapsedSeconds).toBe(2.5); }); });

describe('construction time and material delivery', () => {
  it('keeps the material work rates at 10 seconds per plank and 15 seconds per stone', () => { expect(BUILD_TIME_PER_PLANK).toBe(10); expect(BUILD_TIME_PER_STONE).toBe(15); });
  it('has no aggregate remaining construction time field', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); expect(building).not.toHaveProperty('remainingConstructionTime'); expect(building).not.toHaveProperty('constructionTime'); });
  it('starts in PLACED and then moves to WAITING_FOR_MATERIAL', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); expect(building.constructionState).toBeUndefined(); startConstruction({}, building, 5000); expect(building.constructionState).toBe(CONSTRUCTION_STATES.PLACED); advanceConstruction(building, 0); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); });
  it('follows PLACED → WAITING_FOR_MATERIAL → BUILDING → WAITING_FOR_MATERIAL → BUILDING → COMPLETED', () => { const state = createGameState(); const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); state.buildings.push(building); state.player.resources.planks = 2; state.player.resources.stone = 1; startConstruction(state, building, 5000); expect(building.constructionState).toBe(CONSTRUCTION_STATES.PLACED); advanceConstruction(building, 0); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); expect(deliverConstructionMaterial(state, building.id, 'planks', 1)).toBe(1); expect(building.constructionState).toBe(CONSTRUCTION_STATES.BUILDING); advanceConstruction(building, 10); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); expect(building.constructionComplete).toBe(false); expect(deliverConstructionMaterial(state, building.id, 'stone', 1)).toBe(1); expect(building.constructionState).toBe(CONSTRUCTION_STATES.BUILDING); advanceConstruction(building, 15); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); expect(building.constructionComplete).toBe(false); expect(deliverConstructionMaterial(state, building.id, 'planks', 1)).toBe(1); expect(building.constructionState).toBe(CONSTRUCTION_STATES.BUILDING); advanceConstruction(building, 10); expect(building.constructionState).toBe(CONSTRUCTION_STATES.COMPLETED); expect(building.constructionComplete).toBe(true); expect(building.active).toBe(true); });
  it('starts one 10-second construction segment when one plank arrives', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; expect(deliverConstructionMaterial(state, building.id, 'planks', 1)).toBe(1); expect(building.currentConstructionMaterial).toBe('planks'); expect(building.constructionTimer).toBe(10); advanceConstruction(building, 9); expect(building.constructionComplete).toBe(false); expect(building.constructionTimer).toBe(1); advanceConstruction(building, 1); expect(building.constructionComplete).toBe(false); expect(building.currentConstructionMaterial).toBe(null); expect(building.constructionTimer).toBe(0); expect(state.player.resources.planks).toBe(0); });
  it('waits when the next construction material has not arrived', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; deliverConstructionMaterial(state, building.id, 'planks', 1); advanceConstruction(building, 10); expect(building.constructionTimer).toBe(0); expect(building.constructionState).toBe('WAITING_FOR_MATERIAL'); advanceConstruction(building, 100); expect(building.constructionTimer).toBe(0); expect(building.constructionComplete).toBe(false); });
  it('continues through already delivered construction units', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 2; deliverConstructionMaterial(state, building.id, 'planks', 2); advanceConstruction(building, 10); expect(building.currentConstructionMaterial).toBe('planks'); expect(building.constructionTimer).toBe(10); advanceConstruction(building, 10); expect(building.currentConstructionMaterial).toBe(null); expect(building.constructionTimer).toBe(0); expect(building.constructionComplete).toBe(false); });
  it('handles mixed delivered materials as independent work segments', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; state.player.resources.stone = 1; deliverConstructionMaterial(state, building.id, 'planks', 1); deliverConstructionMaterial(state, building.id, 'stone', 1); advanceConstruction(building, 10); expect(building.currentConstructionMaterial).toBe('stone'); expect(building.constructionTimer).toBe(15); advanceConstruction(building, 15); expect(building.constructionComplete).toBe(false); expect(building.constructionTimer).toBe(0); });
  it('accepts no more material than the building requires and cannot deliver without stock', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; expect(deliverConstructionMaterial(state, building.id, 'planks', 5)).toBe(1); expect(deliverConstructionMaterial(state, building.id, 'planks', 1)).toBe(0); expect(building.constructionMaterialsDelivered.planks).toBe(1); });
  it('allows two buildings to advance independently', () => { const state = createGameState(); const a = createBuilding('a', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const b = createBuilding('b', 'player', BUILDING_TYPES.WAREHOUSE.id, '60-60'); state.buildings.push(a, b); state.player.resources.planks = 5; state.player.resources.stone = 3; deliverConstructionMaterial(state, a.id, 'planks', 1); deliverConstructionMaterial(state, b.id, 'planks', 1); deliverConstructionMaterial(state, b.id, 'stone', 1); advanceConstruction(a, 10); advanceConstruction(b, 10); expect(a.constructionComplete).toBe(false); expect(a.constructionTimer).toBe(0); expect(b.currentConstructionMaterial).toBe('stone'); expect(b.constructionTimer).toBe(15); });
  it('does not move a construction timer backwards or below zero', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 2; deliverConstructionMaterial(state, building.id, 'planks', 2); advanceConstruction(building, 0); expect(building.constructionTimer).toBe(10); advanceConstruction(building, -5); expect(building.constructionTimer).toBe(10); advanceConstruction(building, 20); expect(building.constructionTimer).toBe(0); expect(building.constructionComplete).toBe(true); expect(building.active).toBe(true); });
  it('starts construction with a timestamp without coupling the timer to the game clock', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); startConstruction({}, building, 5000); expect(building.constructionStartedAt).toBe(5000); expect(building.constructionState).toBe(CONSTRUCTION_STATES.PLACED); });
});
