import { describe, expect, it } from 'vitest';
import { createGameState, MAP_WIDTH, MAP_HEIGHT, HEADQUARTERS_INFLUENCE_RADIUS, STARTER_FOREST_AREA, STARTER_STONE_AREA, STARTER_HILLS_AREA, STARTER_MOUNTAINS_AREA } from '../src/game/state.js';
import { BUILDING_TYPES, BUILD_TIME_PER_PLANK, BUILD_TIME_PER_STONE, advanceConstruction, canBuildOnTile, getFootprintTiles, getReservedTiles, isReservedForBuilding, createBuilding } from '../src/game/buildings.js';
import { deliverConstructionMaterial } from '../src/game/materials.js';
import { createGameClock, startGameClock, tickGameClock } from '../src/game/clock.js';
import { startConstruction } from '../src/game/construction.js';
import { INFLUENCE_RADIUS, isWithinInfluenceRadius } from '../src/game/influence.js';
import { WORKER_TYPES, createWorker, createWorkZone, assignWorkerToBuilding, workWorker } from '../src/game/workers.js';
import { createTerritorySource, addTerritorySource, getOwnedTiles } from '../src/game/territory.js';

describe('game clock', () => { it('starts at zero and advances by elapsed seconds', () => { const clock = createGameClock(); expect(clock.elapsedSeconds).toBe(0); startGameClock(clock, 1000); tickGameClock(clock, 3500); expect(clock.elapsedSeconds).toBe(2.5); }); });

describe('construction time and material delivery', () => {
  it('keeps the material work rates at 10 seconds per plank and 15 seconds per stone', () => { expect(BUILD_TIME_PER_PLANK).toBe(10); expect(BUILD_TIME_PER_STONE).toBe(15); });
  it('has no aggregate remaining construction time field', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); expect(building).not.toHaveProperty('remainingConstructionTime'); expect(building).not.toHaveProperty('constructionTime'); });
  it('starts one 10-second construction segment when one plank arrives', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; expect(deliverConstructionMaterial(state, building.id, 'planks', 1)).toBe(1); expect(building.currentConstructionMaterial).toBe('planks'); expect(building.constructionTimer).toBe(10); advanceConstruction(building, 9); expect(building.constructionComplete).toBe(false); expect(building.constructionTimer).toBe(1); advanceConstruction(building, 1); expect(building.constructionComplete).toBe(false); expect(building.currentConstructionMaterial).toBe(null); expect(building.constructionTimer).toBe(0); expect(state.player.resources.planks).toBe(0); });
  it('waits when the next construction material has not arrived', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; deliverConstructionMaterial(state, building.id, 'planks', 1); advanceConstruction(building, 10); expect(building.constructionTimer).toBe(0); expect(building.constructionState).toBe('WAITING_FOR_MATERIAL'); advanceConstruction(building, 100); expect(building.constructionTimer).toBe(0); expect(building.constructionComplete).toBe(false); });
  it('continues through already delivered construction units', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 2; deliverConstructionMaterial(state, building.id, 'planks', 2); advanceConstruction(building, 10); expect(building.currentConstructionMaterial).toBe('planks'); expect(building.constructionTimer).toBe(10); advanceConstruction(building, 10); expect(building.currentConstructionMaterial).toBe(null); expect(building.constructionTimer).toBe(0); expect(building.constructionComplete).toBe(false); });
  it('handles mixed delivered materials as independent work segments', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; state.player.resources.stone = 1; deliverConstructionMaterial(state, building.id, 'planks', 1); deliverConstructionMaterial(state, building.id, 'stone', 1); advanceConstruction(building, 10); expect(building.currentConstructionMaterial).toBe('stone'); expect(building.constructionTimer).toBe(15); advanceConstruction(building, 15); expect(building.constructionComplete).toBe(false); expect(building.constructionTimer).toBe(0); });
  it('accepts no more material than the building requires and cannot deliver without stock', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 1; expect(deliverConstructionMaterial(state, building.id, 'planks', 5)).toBe(1); expect(deliverConstructionMaterial(state, building.id, 'planks', 1)).toBe(0); expect(building.constructionMaterialsDelivered.planks).toBe(1); });
  it('allows two buildings to advance independently', () => { const state = createGameState(); const a = createBuilding('a', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const b = createBuilding('b', 'player', BUILDING_TYPES.WAREHOUSE.id, '60-60'); state.buildings.push(a, b); state.player.resources.planks = 5; state.player.resources.stone = 3; deliverConstructionMaterial(state, a.id, 'planks', 1); deliverConstructionMaterial(state, b.id, 'planks', 1); deliverConstructionMaterial(state, b.id, 'stone', 1); advanceConstruction(a, 10); advanceConstruction(b, 10); expect(a.constructionComplete).toBe(false); expect(a.constructionTimer).toBe(0); expect(b.currentConstructionMaterial).toBe('stone'); expect(b.constructionTimer).toBe(15); });
  it('does not move a construction timer backwards or below zero', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); state.buildings.push(building); state.player.resources.planks = 2; deliverConstructionMaterial(state, building.id, 'planks', 2); advanceConstruction(building, 0); expect(building.constructionTimer).toBe(10); advanceConstruction(building, -5); expect(building.constructionTimer).toBe(10); advanceConstruction(building, 20); expect(building.constructionTimer).toBe(0); expect(building.constructionComplete).toBe(true); expect(building.active).toBe(true); });
  it('starts construction with a timestamp without coupling the timer to the game clock', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); startConstruction({}, building, 5000); expect(building.constructionStartedAt).toBe(5000); expect(building.constructionState).toBe('WAITING_FOR_MATERIAL'); });
});

describe('starter map', () => {
  it('creates a 100x100 map', () => { const state = createGameState(); expect(state.tiles).toHaveLength(MAP_WIDTH * MAP_HEIGHT); });
  it('keeps headquarters influence at radius 10', () => { const state = createGameState(); expect(state.rules.headquartersInfluenceRadius).toBe(HEADQUARTERS_INFLUENCE_RADIUS); expect(HEADQUARTERS_INFLUENCE_RADIUS).toBe(10); });
  it('contains forest and stone deposits on plains plus dedicated hills and mountains', () => { const state = createGameState(); const stone = state.tiles.find((t) => t.x >= STARTER_STONE_AREA.minX && t.x <= STARTER_STONE_AREA.maxX && t.y >= STARTER_STONE_AREA.minY && t.y <= STARTER_STONE_AREA.maxY); const forest = state.tiles.find((t) => t.x >= STARTER_FOREST_AREA.minX && t.x <= STARTER_FOREST_AREA.maxX && t.y >= STARTER_FOREST_AREA.minY && t.y <= STARTER_FOREST_AREA.maxY); const hills = state.tiles.find((t) => t.x >= STARTER_HILLS_AREA.minX && t.x <= STARTER_HILLS_AREA.maxX && t.y >= STARTER_HILLS_AREA.minY && t.y <= STARTER_HILLS_AREA.maxY); const mountains = state.tiles.find((t) => t.x >= STARTER_MOUNTAINS_AREA.minX && t.x <= STARTER_MOUNTAINS_AREA.maxX && t.y >= STARTER_MOUNTAINS_AREA.minY && t.y <= STARTER_MOUNTAINS_AREA.maxY); expect(stone.terrain).toBe('plains'); expect(stone.resources.stone).toBe(25); expect(forest.terrain).toBe('forest'); expect(forest.resources.wood).toBe(9); expect(hills.terrain).toBe('hills'); expect(mountains.terrain).toBe('mountains'); });
});

describe('buildings', () => {
  it('defines exactly the 21 agreed building types', () => { expect(Object.keys(BUILDING_TYPES)).toHaveLength(21); });
  it('uses planks as construction material', () => { expect(BUILDING_TYPES.WAREHOUSE.constructionMaterials).toEqual({ planks: 3, stone: 3 }); expect(BUILDING_TYPES.SAWMILL.constructionMaterials).toEqual({ planks: 2, stone: 2 }); });
  it('allows regular buildings on plains and rejects them on forest', () => { const state = createGameState(); const plain = state.tiles.find((t) => t.x >= 35 && t.x <= 45 && t.y >= 45 && t.y <= 55 && t.terrain === 'plains' && t.influence.player === 1); const forest = state.tiles.find((t) => t.terrain === 'forest'); expect(plain).toBeTruthy(); expect(canBuildOnTile(state, BUILDING_TYPES.WAREHOUSE.id, plain.id)).toBe(true); expect(canBuildOnTile(state, BUILDING_TYPES.WAREHOUSE.id, forest.id)).toBe(false); });
  it('allows mines on hills and mountains', () => { const state = createGameState(); const hills = state.tiles.find((t) => t.terrain === 'hills' && t.x >= 43 && t.x <= 44 && t.y >= 54 && t.y <= 55); const mountains = state.tiles.find((t) => t.terrain === 'mountains' && t.x >= 56 && t.x <= 57 && t.y >= 43 && t.y <= 44); expect(canBuildOnTile(state, BUILDING_TYPES.IRON_MINE.id, hills.id)).toBe(true); expect(canBuildOnTile(state, BUILDING_TYPES.IRON_MINE.id, mountains.id)).toBe(true); });
  it('calculates the complete footprint for a building', () => { const state = createGameState(); const plain = state.tiles.find((t) => t.x >= 35 && t.x <= 45 && t.y >= 45 && t.y <= 55 && t.terrain === 'plains' && t.influence.player === 1); expect(plain).toBeTruthy(); expect(getFootprintTiles(state, BUILDING_TYPES.WAREHOUSE.id, plain.id)).toHaveLength(9); });
  it('creates a one-cell reservation around the footprint', () => { const state = createGameState(); const plain = state.tiles.find((t) => t.x >= 35 && t.x <= 45 && t.y >= 45 && t.y <= 55 && t.terrain === 'plains' && t.influence.player === 1); const reserved = getReservedTiles(state, BUILDING_TYPES.WAREHOUSE.id, plain.id); expect(reserved.length).toBeGreaterThan(0); expect(reserved.every((tile) => !getFootprintTiles(state, BUILDING_TYPES.WAREHOUSE.id, plain.id).includes(tile))).toBe(true); });
  it('allows reservation overlap but blocks building placement in reservation', () => { const state = createGameState(); const a = state.tiles.find((t) => t.x >= 35 && t.x <= 45 && t.y >= 45 && t.y <= 55 && t.terrain === 'plains' && t.influence.player === 1); const reserved = getReservedTiles(state, BUILDING_TYPES.WAREHOUSE.id, a.id); expect(reserved.length).toBeGreaterThan(0); expect(isReservedForBuilding({ ...state, buildings: [{ ...state.buildings[0], typeId: BUILDING_TYPES.WAREHOUSE.id, tileId: a.id }] }, reserved[0].id)).toBe(true); });
});

describe('workers and work zones', () => {
  it('uses radius five for work zones', () => { expect(createWorkZone('z', 'player', '50-50').radius).toBe(5); });
  it('rejects an incompatible worker', () => { const state = createGameState(); const worker = createWorker('w', 'player', WORKER_TYPES.LUMBERJACK.id); state.workers.push(worker); expect(() => assignWorkerToBuilding(state, worker.id, state.buildings[0].id)).toThrow(); });
  it('lets a stonemason extract stone from the designated plains deposit', () => { const state = createGameState(); const tile = state.tiles.find((t) => t.x >= STARTER_STONE_AREA.minX && t.x <= STARTER_STONE_AREA.maxX && t.y >= STARTER_STONE_AREA.minY && t.y <= STARTER_STONE_AREA.maxY && t.terrain === 'plains'); expect(tile).toBeTruthy(); const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); building.active = true; state.buildings.push(building); const zone = createWorkZone('zone-1', 'player', '40-40', 20, building.id); state.workZones.push(zone); const worker = createWorker('worker-1', 'player', WORKER_TYPES.STONEMASON.id); state.workers.push(worker); assignWorkerToBuilding(state, worker.id, building.id, tile.id); const result = workWorker(state, worker.id); expect(result.extracted).toBe(true); expect(result.amount).toBe(1); expect(tile.resources.stone).toBe(24); expect(state.player.resources.stone).toBe(1); });
});

describe('territory', () => {
  it('uses the normal influence radius of five', () => { expect(INFLUENCE_RADIUS).toBe(5); expect(isWithinInfluenceRadius({ x: 0, y: 0 }, { x: 5, y: 0 })).toBe(true); expect(isWithinInfluenceRadius({ x: 0, y: 0 }, { x: 6, y: 0 })).toBe(false); });
  it('expands from an additional source', () => { const state = createGameState(); const before = getOwnedTiles(state, 'player').length; addTerritorySource(state, createTerritorySource('extra', 'player', '80-80', 1, 5)); expect(getOwnedTiles(state, 'player').length).toBeGreaterThan(before); });
});
