import { describe, expect, it } from 'vitest';
import { createGameState, MAP_WIDTH, MAP_HEIGHT, HEADQUARTERS_INFLUENCE_RADIUS, STARTER_FOREST_AREA, STARTER_STONE_AREA, STARTER_HILLS_AREA, STARTER_MOUNTAINS_AREA } from '../src/game/state.js';
import { BUILDING_TYPES, canBuildOnTile, getFootprintTiles, getReservedTiles, isReservedForBuilding, createBuilding } from '../src/game/buildings.js';
import { createGameClock, startGameClock, tickGameClock } from '../src/game/clock.js';
import { BUILD_TIME_PER_PLANK, BUILD_TIME_PER_STONE, CONSTRUCTION_STATES, startConstruction, advanceConstruction } from '../src/game/construction.js';
import { INFLUENCE_RADIUS, isWithinInfluenceRadius } from '../src/game/influence.js';
import { WORKER_TYPES, createWorker, createWorkZone, assignWorkerToBuilding, workWorker } from '../src/game/workers.js';
import { createTerritorySource, addTerritorySource, getOwnedTiles } from '../src/game/territory.js';
import { deliverConstructionMaterialViaLogistics } from './constructionLogisticsHelper.js';

function addConstructionFlag(state, building) { building.flagId = `${building.id}-flag`; state.flags.push({ id: building.flagId, buildingId: building.id, ownerId: building.ownerId, x: 40, y: 40, constructionStorage: {} }); }

describe('game clock', () => { it('starts at zero and advances by whole simulation ticks', () => { const clock = createGameClock(); expect(clock.elapsedSeconds).toBe(0); expect(clock.simulationTicks).toBe(0); startGameClock(clock, 1000); expect(tickGameClock(clock, 3500)).toBe(2); expect(clock.elapsedSeconds).toBe(2); expect(clock.simulationTicks).toBe(2); expect(clock.realTimeAccumulator).toBe(0.5); }); });

describe('construction time and material delivery', () => {
  it('keeps the material work rates at 10 seconds per plank and 15 seconds per stone', () => { expect(BUILD_TIME_PER_PLANK).toBe(10); expect(BUILD_TIME_PER_STONE).toBe(15); });
  it('has no aggregate remaining construction time field', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); expect(building).not.toHaveProperty('remainingConstructionTime'); expect(building).not.toHaveProperty('constructionTime'); });
  it('starts in PLACED and then moves to WAITING_FOR_MATERIAL', () => { const state = createGameState(); const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building, 5000); expect(building.constructionState).toBe(CONSTRUCTION_STATES.PLACED); advanceConstruction(state, building, 0); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); });
  it('follows construction states through physical deliveries and builder processing', () => { const state = createGameState(); const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building); advanceConstruction(state, building, 0); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 3)).toBe(3); advanceConstruction(state, building, 30); expect(building.constructionMaterialsUsed.planks).toBe(3); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); expect(deliverConstructionMaterialViaLogistics(state, building, 'stone', 3)).toBe(3); advanceConstruction(state, building, 45); expect(building.constructionState).toBe(CONSTRUCTION_STATES.COMPLETED); expect(building.constructionComplete).toBe(true); });
  it('starts one 10-second segment after the builder takes a plank from the flag', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 1)).toBe(1); expect(state.flags.find((flag) => flag.buildingId === building.id).constructionStorage.planks).toBe(1); advanceConstruction(state, building, 0); expect(building.currentConstructionMaterial).toBe('planks'); expect(building.constructionTimer).toBe(10); advanceConstruction(state, building, 9); expect(building.constructionTimer).toBe(1); advanceConstruction(state, building, 1); expect(building.currentConstructionMaterial).toBe(null); });
  it('waits when the next material has not reached the construction flag', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 1)).toBe(1); advanceConstruction(state, building, 10); expect(building.constructionState).toBe(CONSTRUCTION_STATES.WAITING_FOR_MATERIAL); expect(building.constructionComplete).toBe(false); });
  it('processes materials in the order they reached the construction flag', () => { const building = createBuilding('warehouse-1', 'player', BUILDING_TYPES.WAREHOUSE.id, '40-40'); const state = createGameState(); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 1)).toBe(1); expect(deliverConstructionMaterialViaLogistics(state, building, 'stone', 1)).toBe(1); expect(building.currentConstructionMaterial).toBe(null); advanceConstruction(state, building, 0); expect(building.currentConstructionMaterial).toBe('planks'); advanceConstruction(state, building, 10); expect(building.currentConstructionMaterial).toBe('stone'); expect(building.constructionTimer).toBe(15); });
  it('does not exceed required material even when more stock is requested', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 5)).toBe(2); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 1)).toBe(0); expect(building.constructionMaterialsDelivered.planks).toBe(2); });
  it('allows two buildings to advance independently', () => { const state = createGameState(); const a = createBuilding('a', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const b = createBuilding('b', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '60-60'); addConstructionFlag(state, a); addConstructionFlag(state, b); state.buildings.push(a, b); startConstruction(state, a); startConstruction(state, b); expect(deliverConstructionMaterialViaLogistics(state, a, 'planks', 2)).toBe(2); expect(deliverConstructionMaterialViaLogistics(state, b, 'planks', 2)).toBe(2); advanceConstruction(state, a, 20); advanceConstruction(state, b, 20); expect(a.constructionComplete).toBe(true); expect(b.constructionComplete).toBe(true); });
  it('does not move a construction timer backwards or below zero', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); addConstructionFlag(state, building); state.buildings.push(building); startConstruction(state, building); expect(deliverConstructionMaterialViaLogistics(state, building, 'planks', 2)).toBe(2); advanceConstruction(state, building, 0); expect(building.constructionTimer).toBe(10); advanceConstruction(state, building, -5); expect(building.constructionTimer).toBe(10); advanceConstruction(state, building, 20); expect(building.constructionComplete).toBe(true); });
  it('starts construction with a timestamp without coupling the timer to the game clock', () => { const building = createBuilding('stonecutter-1', 'player', BUILDING_TYPES.STONECUTTER_HUT.id, '40-40'); const state = createGameState(); addConstructionFlag(state, building); startConstruction(state, building, 5000); expect(building.constructionStartedAt).toBe(5000); expect(building.constructionState).toBe(CONSTRUCTION_STATES.PLACED); });
});

// Keep the game-state imports above part of the public test contract.
void MAP_WIDTH; void MAP_HEIGHT; void HEADQUARTERS_INFLUENCE_RADIUS; void STARTER_FOREST_AREA; void STARTER_STONE_AREA; void STARTER_HILLS_AREA; void STARTER_MOUNTAINS_AREA; void INFLUENCE_RADIUS; void isWithinInfluenceRadius; void WORKER_TYPES; void createWorker; void createWorkZone; void assignWorkerToBuilding; void workWorker; void createTerritorySource; void addTerritorySource; void getOwnedTiles; void getReservedTiles; void isReservedForBuilding;
