import { getSelectedTile } from '../game/state.js';
import { TERRAIN_BY_ID } from '../game/terrain.js';
import { getTerritorySourceAtTile } from '../game/territory.js';
import { BUILDING_TYPES, getBuildingAtTile, getConstructionTime } from '../game/buildings.js';

const WORKER_NAMES = { lumberjack: 'Лесоруб', stonemason: 'Каменщик', miner: 'Шахтёр' };
const BUILDING_ICONS = { headquarters: '🏛️', warehouse: '📦', forester_hut: '🌲', stonecutter_hut: '🪨', sawmill: '🪚', well: '💧', farm: '🌾', mill: '⚙️', bakery: '🥖', coal_mine: '⛏️', iron_mine: '⛏️', gold_mine: '🟡', marble_mine: '🪨', foundry: '🔥', forge: '⚒️', workshop: '🛠️', mint: '🪙', outpost: '🏕️', barracks: '🏰', watchtower: '🗼', fortress: '🏯' };

export function getBuildMenuTypes() { return Object.values(BUILDING_TYPES).filter((type) => type.id !== 'headquarters').map((type, index) => ({ ...type, constructionCostTotal: Object.values(type.cost).reduce((sum, value) => sum + Number(value || 0), 0), originalIndex: index })).sort((a, b) => a.constructionCostTotal - b.constructionCostTotal || a.originalIndex - b.originalIndex); }

export function renderBuildMenu(container, state, selectedBuildingTypeId = null) { const types = getBuildMenuTypes(); const { resources } = state.player; container.innerHTML = `<div class="build-menu" aria-label="Строительство"><div class="build-menu-title">Строительство</div>${types.map((type) => { const affordable = Object.entries(type.cost).every(([resource, amount]) => (resources[resource] ?? 0) >= amount); const cost = Object.entries(type.cost).map(([resource, amount]) => `${amount} ${resource === 'planks' ? '🪵' : resource === 'stone' ? '🪨' : resource}`).join(' + '); const selected = type.id === selectedBuildingTypeId ? ' is-selected' : ''; return `<button class="build-item${selected}" type="button" data-action="select-building" data-type-id="${type.id}" ${affordable ? '' : 'data-unaffordable="true"'}><span class="build-item-icon">${BUILDING_ICONS[type.id] ?? '🏗️'}</span><span class="build-item-info"><strong>${type.name}</strong><small>${cost}</small><small>Строительство: ${getConstructionTime(type.cost)} с</small></span></button>`; }).join('')}</div>`; }

export function renderPlayerPanel(container, state) { const { resources } = state.player; const ownedTiles = state.tiles.filter((tile) => tile.ownerId === state.player.id).length; const sources = (state.territorySources ?? []).filter((source) => source.ownerId === state.player.id && source.active).length; const buildings = (state.buildings ?? []).filter((building) => building.ownerId === state.player.id && building.active).length; const workers = (state.workers ?? []).filter((worker) => worker.ownerId === state.player.id).length; container.innerHTML = `<div class="stat"><span>Территория</span><strong>${ownedTiles}</strong></div><div class="stat"><span>Здания</span><strong>${buildings}</strong></div><div class="stat"><span>Рабочие</span><strong>${workers}</strong></div><div class="stat"><span>Источники влияния</span><strong>${sources}</strong></div><div class="stat"><span>Дерево</span><strong>${resources.wood ?? resources.planks ?? 0}</strong></div><div class="stat"><span>Камень</span><strong>${resources.stone ?? 0}</strong></div><div class="stat"><span>Еда</span><strong>${resources.food ?? 0}</strong></div>`; }

export function renderTilePanel(container, state, selectedBuildingTypeId = null) { const tile = getSelectedTile(state); if (!tile) { container.textContent = 'Выберите клетку.'; return; } const terrain = TERRAIN_BY_ID[tile.terrain]; const source = getTerritorySourceAtTile(state, tile.id); const building = getBuildingAtTile(state, tile.id); const workers = building ? (state.workers ?? []).filter((worker) => worker.buildingId === building.id) : []; const zone = building ? state.workZones?.find((item) => item.buildingId === building.id) : null; const resourceLines = Object.entries(tile.resources).filter(([, amount]) => amount > 0).map(([resource, amount]) => `${resource}: ${amount}`).join(', '); const influenceLines = Object.entries(tile.influence).map(([actor, amount]) => `${actor}: ${amount}`).join(', ') || 'нет'; const canBuildSource = tile.ownerId === state.player.id && !source; const selectedType = selectedBuildingTypeId ? Object.values(BUILDING_TYPES).find((item) => item.id === selectedBuildingTypeId) : null; container.innerHTML = `<div class="stat"><span>Координаты</span><strong>${tile.x}, ${tile.y}</strong></div><div class="stat"><span>Ландшафт</span><strong>${terrain?.name ?? tile.terrain}</strong></div><div class="stat"><span>Владелец</span><strong>${tile.ownerId ?? 'нет'}</strong></div><div class="stat"><span>Ресурсы</span><strong>${resourceLines || 'нет'}</strong></div><div class="stat"><span>Влияние</span><strong>${influenceLines}</strong></div><div class="stat"><span>Источник</span><strong>${source?.id ?? 'нет'}</strong></div>${building ? `<div class="stat"><span>Здание</span><strong>${building.typeId}</strong></div><div class="stat"><span>Рабочая зона</span><strong>R=${zone?.radius ?? 5}</strong></div><div class="stat"><span>Работники</span><strong>${workers.map((worker) => WORKER_NAMES[worker.typeId] ?? worker.typeId).join(', ') || 'нет'}</strong></div>` : ''}${selectedType && !building ? `<button class="panel-action" type="button" data-action="build">Построить ${selectedType.name}</button>` : ''}${canBuildSource ? '<button class="panel-action" type="button" data-action="build-source">Разместить источник влияния</button>' : ''}`; }

export function renderTurnInfo(container, state) { container.textContent = `Ход: ${state.turn} · Радиус влияния/рабочей зоны: ${state.rules.influenceRadius}`; }
